# Generated by Django 5.1.1 on 2024-09-07 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.CharField(default='', max_length=100, verbose_name='author'),
            preserve_default=False,
        ),
    ]
