# Generated by Django 5.1.1 on 2024-09-09 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_bookborrowrequest_return_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterModelOptions(
            name='bookborrowrequest',
            options={'ordering': ('-created_at',)},
        ),
    ]
